# Combine VCF files from several callers into one
# The following files are combined:
# * strelka SNV         ("strelka")
# * strelka indel       ("sindel")
# * varscan SNV         ("varscan")
# * varscan indel       ("varindel")
# * mutect SNV          ("mutect")
# * pindel indel        ("pindel")

# --bypass_merge - skips merge filter by retaining all reads
# $bypass is an optional flag which if set will bypass the filter and retain all reads

# After merging, all VCFs together, we filter to retain only those variants which are called by 2/3 callers

# CWL-specific changes
# * Get rid of unused arguments
# * pass all input VCFs
# * Output port: merged/merged.filtered.vcf

sub merge_vcf {
    my $results_dir = shift;
    my $job_files_dir = shift;
    my $REF = shift;

    my $strelka_snv_vcf = shift;
    my $strelka_indel_vcf = shift; # new
    my $varscan_snv_vcf = shift;
    my $varscan_indel_vcf = shift;
    my $mutect_vcf = shift; # new
    my $pindel_vcf = shift;
    my $bypass_merge = shift;
    my $debug = shift;


    my $bypass_str = $bypass_merge ? "--bypass_merge" : "";
    my $debug_str = $debug ? "--debug" : "";

    my $filter_results = "$results_dir/merged";
    system("mkdir -p $filter_results");


    my $merger_out_tmp = "$filter_results/merged.vcf";
    my $merger_out = "$filter_results/merged.filtered.vcf";

    my $runfn = "$job_files_dir/j8_merge_vcf.sh";
    print STDERR "Writing to $runfn\n";
    open(OUT, ">$runfn") or die $!;

# Testing indicates there are issues merging Mutect VCF having to do with incompatible contigs: mutect is subset of reference.
# Solution is to use flag below to turn errors into warnings; see discussion in README.md:
# -U ALLOW_SEQ_DICT_INCOMPATIBILITY
# Updating merge order.  Previously: strelka,varscan,mutect,sindel,varindel,pindel
#   Changing to: varscan,mutect,strelka,varindel,pindel,sindel
# Reason for change is to retain varscan's superior FORMAT information, which has genotype (GT) and other details

    print OUT <<"EOF";
#!/bin/bash
export JAVA_OPTS=\"-Xmx2g\"
 java \$JAVA_OPTS -jar $SWpaths::gatk_jar -R $REF -T CombineVariants -o $merger_out_tmp \\
    --variant:varscan $varscan_snv_vcf \\
    --variant:strelka $strelka_snv_vcf \\
    --variant:mutect $mutect_vcf \\
    --variant:varindel $varscan_indel_vcf \\
    --variant:sindel $strelka_indel_vcf \\
    --variant:pindel $pindel_vcf \\
    -genotypeMergeOptions PRIORITIZE -priority varscan,mutect,strelka,varindel,pindel,sindel \\
    -U ALLOW_SEQ_DICT_INCOMPATIBILITY

# Evaluate return value see https://stackoverflow.com/questions/90418/exit-shell-script-based-on-process-exit-code
rc=\$?
if [[ \$rc != 0 ]]; then
    >&2 echo Fatal error \$rc: \$!.  Exiting.
    exit \$rc;
fi
 
>&2 echo Merged unfiltered VCF written to $merger_out_tmp

>&2 echo Filter merged VCF file to exclude snv calls generated by just one caller.
export PYTHONPATH="$SWpaths::filter_dir:\$PYTHONPATH"
bash $SWpaths::filter_dir/run_merged_filter.sh $merger_out_tmp $merger_out $bypass_str $debug_str

rc=\$?
if [[ \$rc != 0 ]]; then
    >&2 echo Fatal error \$rc: \$!.  Exiting.
    exit \$rc;
fi

>&2 echo Written final result to $merger_out

EOF

    close OUT;
    my $cmd = "bash < $runfn\n";
    print STDERR "Executing:\n $cmd \n";

    my $return_code = system ( $cmd );
    die("Exiting ($return_code).\n") if $return_code != 0;
}

1;
